# Generated by Django 4.2.23 on 2025-06-23 02:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pybo', '0003_answer_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='voter',
            field=models.ManyToManyField(blank=True, related_name='voter_question', to=settings.AUTH_USER_MODEL),
        ),
    ]
